# Generated by Django 2.1.15 on 2021-01-23 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbbackup_sum', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dbbackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Detal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nakladnaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detal_number', models.IntegerField()),
                ('detal_name', models.CharField(max_length=100)),
                ('recive_date', models.DateField(default=datetime.date.today)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proizvodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rabotnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sum', models.IntegerField(blank=True)),
                ('last_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skladApp.Nakladnaya')),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('square', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SkladAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stanok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('lifetime', models.IntegerField()),
                ('proizvodstvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.Proizvodstvo')),
            ],
        ),
        migrations.CreateModel(
            name='systemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25)),
                ('number', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=150)),
                ('birhtday', models.DateField(default=datetime.date.today)),
                ('position', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('user_base', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skladadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.systemUser'),
        ),
        migrations.AddField(
            model_name='rabotnik',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.systemUser'),
        ),
        migrations.AddField(
            model_name='nakladnaya',
            name='remontnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.systemUser'),
        ),
        migrations.AddField(
            model_name='nakladnaya',
            name='sklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.Sklad'),
        ),
        migrations.AddField(
            model_name='detal',
            name='sklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.Sklad'),
        ),
        migrations.AddField(
            model_name='detal',
            name='stanok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.Stanok'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='dbbackup_last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skladApp.Dbbackup'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skladApp.systemUser'),
        ),
    ]
